name: Label pull request

on:
  pull_request_target:
    branches:
      - main

jobs:
  labeler:
    name: Apply labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
